### ISSUE TITLE
Overwriting of module.config.php resolves magic constants like __DIR__ 

### ISSUE THREAD

**Issue by hoppithek** [ZFrapid/zf2rapid#10]
Overwriting of config files does not preserve the usage of `__DIR__` constant, and presumably any other magic constant as well.

**Comment by RalfEggert** [comment]
ZF2rapid already supported the `APPLICATION_ROOT` constant and a specific root constant for the current module, e.g `SHOP_MODULE_ROOT` for a `Shop` Module. With commit https://github.com/ZFrapid/zf2rapid/commit/a157f8dcfd15c83316f4fe2a92cc268098fac6a7 I also added support for the `__DIR__` constant. 

Please check.

Which other magic constants should be supported?

**Comment by hoppithek** [comment]
Thanks, for commit!

I didn't look at the code yet. but if is just a matter of naming them, than I would say all magic constants (not so many anyways, or simple all starting and ending in double underscore) plus as many predefined as wanted. I don't have access to my testing environment right now, but I think I remember a zf2rapid.json with configuration in it, why not extend it to include a list of constants to be kept?

If it is a matter of a hand picked few that can be rescued to the other side, than `__DIR__` seems the most important to me. Maybe getenv('some_identifier') calls and getcwd() should be preserved as well.

**Comment by RalfEggert** [comment]
Well, it is not just the matter of naming then. Before the config is written, I just check the values and replace any matching paths with the `APPLICATION_ROOT` constant, the module specific constants like `SHOP_MODULE_ROOT` and the `__DIR__`. Thats quite easy to do.

But I am afraid its almost impossible to do it for calles like `getenv('some_identifier')` because the config files are included first, then changed and then written again. After the inclusion of the config file, all constants and function calls will be processed and get lost.

So, I guess, I will have no easy solution for this request in the near future and I am tending to label this issue as a `won't fix`.

**Comment by hoppithek** [comment]
If it wont fix, it wont fix, I guessed as much, but you never know before you ask. If changing/overwriting the config files can be made optional with a command line switch than that will be good enough. If you have configs, that include programmatic content, than you are on your own, when it comes to config changes, sounds reasonable.

Thanks for looking into this.

**Comment by RalfEggert** [comment]
Well, you can always use a config script with logic that reads the static `application.config.php` file. 

Will close this now. But could be reopened some day if others request such a feature.
