### ISSUE TITLE
Ideas for new configuration options

### ISSUE THREAD

**Issue by Koopzington** [ZFrapid/zf2rapid#14]
It'd be nice if the user could decide which array syntax (<code>array()</code> or <code>[]</code>) should be used.
It'd also be cool to let the user decide if he wants to have either have class names like this
```PHP
'controllers' => array(
    'factories' => array(
        'Module\Controller\FooController' => 'Module\Controller\FooControllerFactory'
    )
)
```
or this
```PHP
'controllers' => array(
    'factories' => array(
        \Module\Controller\FooController::class => \Module\Controller\FooControllerFactory::class
    )
)
```

**Comment by RalfEggert** [comment]
I am currently implementing the short array syntax stuff. Need to check the `class` constant stuff. I am not sure if `Zend\Code` can handle the writing of that properly.

**Comment by froschdesign** [comment]
@Koopzington 
> It'd be nice if the user could decide which array syntax (array() or []) should be used.

Why? (Useless option.)

> It'd also be cool to let the user decide if he wants to have either have class names like this

The same here: Why?

@RalfEggert 
Don't waste time and resources.

**Comment by RalfEggert** [comment]
Well, I changed the code of ZF2rapid now to short array syntax. I wanted to do it since a long time, but forgot it. 

Regarding generating short array syntax code it is more complicated. `Zend\Code\Generator\ValueGenerator` always generates the "old" array syntax and it is not configurable. So the `ValueGenerator` needs to be changed first.

@froschdesign Like you I am not sure if the class name stuff is really worth the effort.

**Comment by RalfEggert** [comment]
Added the array short syntax stuff now. The other issue needs more time. I will close this issue for now. 

If may others would need this we could reopen this issue again later on.
