### ISSUE TITLE
Idea: Make factory paths configurable

### ISSUE THREAD

**Issue by Danielss89** [ZFrapid/zf2rapid#17]
Just found this project, and it looks pretty cool. It would be cool if it was possible to specify the path where you want factories to be located.
For example, i put all my factories under a Factory namespace.
`module/Application/src/Application/Factory/Controller/IndexControllerFactory`
`module/Application/src/Application/Factory/Service/UserServiceFactory`

**Comment by RalfEggert** [comment]
@Danielss89 

Thanks for your request. 

But to be honest, I personally think, that keeping all factories in a special path is a bad practice. You need to build the same directory tree under your `module/Application/src/Application/Factory/` path that you already have under `module/Application/src/Application/`. To handle this and the current way of keeping classes and factories in the same directory will need additional configuration or command flags.

So I am sorry, I won't implement this in the near future due to limited free time. If this request is supported by significant number of users, it might come some day. But for now I will close this.
